### ISSUE TITLE
Brand new Next 13 site -> add Typewriter -> error

### ISSUE THREAD

**Issue by lukeocodes** [tameemsafi/typewriterjs#195]
I've just created a new Next 13 site. I simply ran the `npx create-next-app@latest` -> `npm i typewriter-effect` -> added the component to the `page.tsx` file and got a render error.

```tsx {page.tsx}
// page.tsx
import Typewriter from "typewriter-effect";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <Typewriter
        options={{
          strings: ["Hello", "World"],
          autoStart: true,
          loop: true,
        }}
      />
    </main>
  );
}
```

The error output:

```bash
(0) lukeocodes~/Projects/Deepgram/deepgram-cli/web(lo/prep-for-beta-release|…) % npm run dev

> @deepgram/cli-web@0.1.0 dev
> next dev

(node:47716) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
(node:47717) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
- event compiled client and server successfully in 250 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 140 ms (20 modules)
- wait compiling /page (client and server)...
- wait compiling /_error (client and server)...
- event compiled client and server successfully in 2.8s (554 modules)
- event compiled client and server successfully (540 modules)
- warn Fast Refresh had to perform a full reload due to a runtime error.
(node:47720) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
- error node_modules/typewriter-effect/dist/react.js (1:28691) @ eval
- error Error [TypeError]: Super expression must either be null or a function
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1196:69)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1206:18)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1288:14)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1293:11)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1294:7)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:3:30)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:4:2)
    at Object.(sc_server)/./node_modules/typewriter-effect/dist/react.js (/Users/lukeoliff/Projects/Deepgram/deepgram-cli/web/.next/server/app/page.js:2152:1)
    at __webpack_require__ (/Users/lukeoliff/Projects/Deepgram/deepgram-cli/web/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./src/app/page.tsx:7:75) {
  digest: undefined
}
null
- error node_modules/typewriter-effect/dist/react.js (1:28691) @ eval
- error Error [TypeError]: Super expression must either be null or a function
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1196:69)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1206:18)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1288:14)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1293:11)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1294:7)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:3:30)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:4:2)
    at Object.(sc_server)/./node_modules/typewriter-effect/dist/react.js (/Users/lukeoliff/Projects/Deepgram/deepgram-cli/web/.next/server/app/page.js:2152:1)
    at __webpack_require__ (/Users/lukeoliff/Projects/Deepgram/deepgram-cli/web/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./src/app/page.tsx:7:75) {
  digest: undefined
}
null
- error node_modules/typewriter-effect/dist/react.js (1:28691) @ eval
- error Error [TypeError]: Super expression must either be null or a function
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1196:69)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1206:18)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1288:14)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1293:11)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:1294:7)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:3:30)
    at eval (webpack-internal:///(sc_server)/./node_modules/typewriter-effect/dist/react.js:4:2)
    at Object.(sc_server)/./node_modules/typewriter-effect/dist/react.js (/Users/lukeoliff/Projects/Deepgram/deepgram-cli/web/.next/server/app/page.js:2152:1)
    at __webpack_require__ (/Users/lukeoliff/Projects/Deepgram/deepgram-cli/web/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./src/app/page.tsx:7:75) {
  digest: undefined
}
null
- wait compiling /favicon.ico/route (client and server)...
- event compiled successfully in 253 ms (296 modules)
(node:47742) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

Any ideas if this is a Next config thing, or a version mismatch, or a bug?

**Comment by lukeocodes** [comment]
Duplicate of #194, my apologies <3
